--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleLay
build-by-default: true
branches:
- master
- php-7.4
projects:
  SimpleLay:
    path: ""
    icon: "/assets/logo.PNG"
...
